# Generated by Django 5.0.4 on 2024-05-20 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('portal', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('IMG_profile', models.ImageField(default='perfiles/anonimo.png', upload_to='perfiles/')),
                ('dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('igual', 'Pagar por igual'), ('porcentajes', 'Pagar por porcentajes')], default='igual', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('valoracion_media', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('IMG_profile', models.ImageField(default='perfiles/anonimo.png', upload_to='perfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('last_chat', models.CharField(max_length=100)),
                ('mensaje_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatReadBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='read_by',
            field=models.ManyToManyField(related_name='read_chats', through='home.ChatReadBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('evento', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_anuncio', models.DateField(blank=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('firmada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('max_attendees', models.PositiveIntegerField(null=True)),
                ('current_attendees', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('visibility', models.CharField(choices=[('publico', 'Publico'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendsChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat')),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_tope', models.DateField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='gastos/')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('numero', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='incidencias/')),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='baja', max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente de aceptar', 'Pendiente de aceptar'), ('Denegada', 'Denegada'), ('Aceptada', 'Aceptada'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada'), ('Trabajando', 'Trabajando'), ('Terminada', 'Terminada'), ('Finalizada', 'Finalizada')], default='Pendiente de aceptar', max_length=20)),
                ('valoracion', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('fecha_tope', models.DateField(null=True)),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos', to='home.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('piscina', 'Piscina'), ('jardineria', 'Jardinería'), ('personal', 'Personal de comunidad'), ('limpieza', 'Limpieza'), ('seguro', 'Seguro Comunidad'), ('fondos', 'Fondos para la Comunidad'), ('extras', 'Extras')], max_length=100, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='SeguroComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, null=True)),
                ('cubre', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('comunidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('fondo', models.CharField(default='clear', max_length=20)),
                ('lang', models.CharField(default='es', max_length=10)),
                ('user_rol', models.CharField(blank=True, max_length=100)),
                ('IMG_profile', models.ImageField(default='perfiles/anonimo.png', upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_comunidad', models.CharField(choices=[('community_president', 'Community President'), ('community_vicepresident', 'Community Vice President'), ('community_user', 'Community User')], default='community_user', max_length=100)),
                ('piso', models.CharField(max_length=100)),
                ('puerta', models.CharField(max_length=100)),
                ('porcentaje_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.evento')),
            ],
            options={
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
