# Generated by Django 5.0.4 on 2024-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_anuncio',
            field=models.DateTimeField(),
        ),
    ]
