# Generated by Django 5.0.4 on 2024-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha_tope',
            field=models.DateField(null=True),
        ),
    ]
