# Generated by Django 5.0.4 on 2024-05-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_user_rol_alter_user_img_profile_alter_user_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
