# Generated by Django 5.0.4 on 2024-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_recibo_fecha_tope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='cantidad_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
