# Generated by Django 5.0.4 on 2024-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_segurocomunidad_empresa_alter_segurocomunidad_cubre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, null=True),
        ),
    ]
