# Generated by Django 5.0.4 on 2024-05-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='fondo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
