# Generated by Django 5.0.4 on 2024-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_motivo_cantidad_alter_motivo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivo',
            name='tipo',
            field=models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('piscina', 'Piscina'), ('jardineria', 'Jardinería'), ('personal', 'Personal de comunidad'), ('limpieza', 'Limpieza'), ('extras', 'Extras')], max_length=100, null=True),
        ),
    ]
