# Generated by Django 5.0.4 on 2024-05-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_motivo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], max_length=20)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.RemoveField(
            model_name='proximospagos',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='ultimosmovimientos',
            name='comunidad',
        ),
        migrations.DeleteModel(
            name='PagosHechos',
        ),
        migrations.DeleteModel(
            name='ProximosPagos',
        ),
        migrations.DeleteModel(
            name='UltimosMovimientos',
        ),
    ]
