# Generated by Django 5.0.4 on 2024-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vivienda_fondo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='fondo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
