# Generated by Django 5.0.4 on 2024-05-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_incidencia_gasto_alter_userprofile_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comunidad'),
        ),
    ]
