# Generated by Django 5.0.4 on 2024-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_vivienda_fondo_userprofile_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='token',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
