# Generated by Django 5.0.4 on 2024-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pagosusuario_delete_historial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], max_length=20, null=True),
        ),
    ]
