# Generated by Django 5.0.4 on 2024-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comunidad_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='numero_cuenta',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='token',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
