# Generated by Django 5.0.4 on 2024-05-03 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_userprofile_img_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('portal', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('IMG_community', models.ImageField(default='anonimus.png', upload_to='profiles/')),
                ('dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('valoracion_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('IMG_profile', models.ImageField(default='anonimus.png', upload_to='profiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='door',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.ImageField(default='anonimus.png', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fondo',
            field=models.CharField(default='clear', max_length=20),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='incidencias/')),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente de aceptar', 'Pendiente de aceptar'), ('Denegada', 'Denegada'), ('Aceptada', 'Aceptada'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada'), ('Trabajando', 'Trabajando'), ('Terminada', 'Terminada'), ('Finalizada', 'Finalizada')], default='Pendiente de aceptar', max_length=20)),
                ('valoracion', models.IntegerField(blank=True, null=True)),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=100)),
                ('puerta', models.CharField(max_length=100)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
