# Generated by Django 5.0.4 on 2024-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_incidencia_comunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='IMG_profile',
            field=models.CharField(default='perfiles/anonimo.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='valoracion',
            field=models.IntegerField(null=True),
        ),
    ]
