# Generated by Django 5.0.4 on 2024-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comunidad_numero_cuenta_alter_comunidad_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosusuario',
            name='cantidad_pagada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
