# Generated by Django 5.0.4 on 2024-05-12 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comunidad_img_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='valoracion',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
