# Generated by Django 5.0.4 on 2024-05-12 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_incidencia_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='valoracion_media',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
