# Generated by Django 5.0.4 on 2024-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comunidad_img_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='IMG_community',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.jpg', max_length=100),
        ),
    ]
