# Generated by Django 5.0.4 on 2024-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_comunidad_img_community_comunidad_img_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.CharField(default='profiles/anonimo.png', max_length=100),
        ),
    ]
