# Generated by Django 5.0.4 on 2024-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_empresa_valoracion_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.CharField(default='perfiles/anonimo.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.ImageField(default='perfiles/anonimo.png', upload_to=''),
        ),
    ]
