# Generated by Django 5.0.4 on 2024-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comunidad_img_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.ImageField(default='profiles/anonimo.png', upload_to='profiles'),
        ),
    ]
