# Generated by Django 5.0.4 on 2024-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_incidencia_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='IMG_profile',
            field=models.ImageField(default='perfiles/anonimo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.ImageField(default='perfiles/anonimo.png', upload_to=''),
        ),
    ]
