# Generated by Django 5.0.4 on 2024-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_comunidad_img_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.ImageField(blank=True, default='perfiles/anonimo.png', upload_to=''),
        ),
    ]
