# Generated by Django 5.0.4 on 2024-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_empresa_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
