# Generated by Django 5.0.4 on 2024-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_incidencia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='IMG_profile',
            field=models.ImageField(default='perfiles/anonimo.png', upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='IMG_profile',
            field=models.ImageField(blank=True, default='perfiles/anonimo.png', upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IMG_profile',
            field=models.ImageField(default='perfiles/default.jpg', upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
