# Generated by Django 5.0.4 on 2024-05-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='user',
            new_name='usuario',
        ),
    ]
