# Generated by Django 5.0.4 on 2024-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_evento_fecha_hora_remove_evento_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='metodo_pago',
            field=models.CharField(choices=[('igual', 'Pagar por igual'), ('porcentajes', 'Pagar por porcentajes')], default='igual', max_length=50),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='porcentaje_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='tipo',
            field=models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('piscina', 'Piscina'), ('jardineria', 'Jardinería'), ('personal', 'Personal de comunidad'), ('limpieza', 'Limpieza'), ('seguro', 'Seguro Comunidad'), ('fondos', 'Fondos para la Comunidad'), ('extras', 'Extras')], max_length=100, null=True),
        ),
    ]
