# Generated by Django 5.0.4 on 2024-05-05 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_chat_chat_read_chatreadby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read_by',
            field=models.ManyToManyField(related_name='read_chats', through='home.ChatReadBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatreadby',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
