# Generated by Django 5.0.4 on 2024-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_chat_read_by_chatreadby_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='rol_comunidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
