# Generated by Django 5.0.4 on 2024-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='evento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
