# Generated by Django 5.0.4 on 2024-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_calendario_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
