# Generated by Django 5.0.4 on 2024-05-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_calendario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comunidad'),
        ),
    ]
