# Generated by Django 5.0.4 on 2024-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
