# Generated by Django 5.0.4 on 2024-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_chat_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
